parameters:
  model_type:
    values:
      - Mamba
  dt_max:
    values:
      - 0.1
  nb_hiddens:
    values:
      - 64
  nb_layers:
    values:
      - 7
  pdrop:
    values:
      - 0.2
  normalization:
    values:
      - layernorm
  lr:
    values:
      - 0.0001
  batch_size:
    values:
      - 32
  scheduler_patience:
    values:
      - 5
  dataset_name:
    values:
      - sc
  data_folder:
    values:
      - ./data/GSC/
  log_tofile:
    values:
      - true

